### ISSUE TITLE
Demo 中没有美颜吧

### ISSUE THREAD

**Issue by Tans5** [joyycom/VNN#13]
SDK支持美颜吗？

**Comment by mrbrantofgithub** [comment]
sdk不支持美颜。人脸关键点可用于帮助开发美颜的功能。

**Comment by Tans5** [comment]
@mrbrantofgithub 谢谢你的回复，^_^.

**Comment by weiyu666** [comment]
美颜是使用的orangefilter 这个渲染引擎开发的吧? 根据人脸点进行三角化做人脸贴纸，或者使用人脸mask进行美白什么的；  @mrbrantofgithub
