### ISSUE TITLE
人脸额外状态（比如：闭眼情况，眨眼情况，张嘴情况）检测没有生效

### ISSUE THREAD

**Issue by Vic1230** [joyycom/VNN#21]
请问，人脸额外状态（比如：闭眼情况，眨眼情况，张嘴情况）检测没有生效，是要做什么额外设置吗？

**Comment by mrbrantofgithub** [comment]
1. VNN_Set_Face_Attr( handle, "_allowFaceAction",  &allowFaceAction); // int allowFaceAction = 1;
2. use VNN_MODE_FMT_VIDEO

**Comment by mrbrantofgithub** [comment]
1. VNN_Set_Face_Attr( handle, "_allowFaceAction", &allowFaceAction); // int allowFaceAction = 1; VNN_Create_Face之后加上这句
2. 在VNN_Apply_Face_CPU的时候设置VNN_MODE_FMT_VIDEO
