### ISSUE TITLE
多次调用VNN_Apply_Face_CPU

### ISSUE THREAD

**Issue by songtianhui** [joyycom/VNN#49]
请问我在使用VNN_Apply_Face_CPU时，第一次调用可以正常检测，但我再输入另一个图像返回就零张人脸了。两张图调换一下顺序也是第一张图能检测到，第二张不能。
请问是不是vnn_handle_的问题，需要每每一张不同的输入图片都创建一个vnn_handle_?

**Comment by AragonMe** [comment]
我是十年，来信已收到

**Comment by mrbrantofgithub** [comment]
图片模式需要设置input.mode_fmt = VNN_MODE_FMT_PICTURE;

**Comment by songtianhui** [comment]
感谢，是这个问题，原来框架代码默认是GPUPIXEL_MODE_FMT_VIDEO。
