### ISSUE TITLE
disney face 和 3D face 如何绘制在位图上

### ISSUE THREAD

**Issue by zhongbaitu** [joyycom/VNN#6]
hello，请教一下，disney face 和 3D face 若想绘制在bitmap上可以怎么做呢？求指点~

**Comment by yuzuhakuon** [comment]
不是创建一个bitmap, 然后填充对应像素点就可以了吗

**Comment by mrbrantofgithub** [comment]
private void blendForegroundBackground(Canvas canvas, Bitmap backImg, VNN.VNN_ImageArr foreData, VNN.VNN_ImageArr maskData) {
        if (canvas == null) {
            return;
        }
        int width = backImg.getWidth();
        int height = backImg.getHeight();
        int totalPixels = width * height;
        @ColorInt int[] argbPixels = new int[totalPixels];
        backImg.getPixels(argbPixels, 0, width, 0, 0, width, height);

        for(int i = 0; i < foreData.imgsNum; i++) {
            float cropLeftFloat = foreData.imgsArr[i].rect[0];
            float cropTopFloat = foreData.imgsArr[i].rect[1];
            float cropRightFloat = foreData.imgsArr[i].rect[2];
            float cropBottomFloat = foreData.imgsArr[i].rect[3];
            int cropLeft = (int)(cropLeftFloat * (width - 1));
            int cropTop = (int)(cropTopFloat * (height - 1));
            int cropRight = (int)(cropRightFloat * (width - 1));
            int cropBottom = (int)(cropBottomFloat * (height - 1));
            int cropWidth = cropRight - cropLeft + 1;
            int cropHeight = cropBottom - cropTop + 1;
            Bitmap maskImg = getBitmapImgFromMask(maskData.imgsArr[i].data, maskData.imgsArr[i].width, maskData.imgsArr[i].height);
            Bitmap fgImg = getBitmapImgFromRGB(foreData.imgsArr[i].data, foreData.imgsArr[i].width, foreData.imgsArr[i].height);
            Bitmap resizeMaskImg = resizeBitmap(maskImg, cropWidth, cropHeight);
            Bitmap resizefgImg = resizeBitmap(fgImg, cropWidth, cropHeight);
            int cropPixels = cropWidth * cropHeight;
            @ColorInt int[] maskPixels = new int[cropPixels];
            @ColorInt int[] fgPixels = new int[cropPixels];
            resizeMaskImg.getPixels(maskPixels, 0, cropWidth, 0, 0, cropWidth, cropHeight);
            resizefgImg.getPixels(fgPixels, 0, cropWidth, 0, 0, cropWidth, cropHeight);
            for (int h = 0; h < cropHeight; ++h) {
                int startH = cropTop + h;

                if (startH < 0) {
                    continue;
                }
                if (startH >= height) {
                    break;
                }
                for (int w = 0; w < cropWidth; ++w) {
                    int startW = cropLeft + w;
                    if (startW < 0) {
                        continue;
                    }
                    if (startW >= width) {
                        break;
                    }
                    int idxBg =startH * width + startW;

                    @ColorInt int bgPixel = argbPixels[idxBg];
                    @ColorInt int maskPixel = maskPixels[h * cropWidth + w];
                    @ColorInt int fgPixel = fgPixels[h * cropWidth + w];
                    float mask_v = Color.red(maskPixel) / 255.f;
                    float alpha = 1.0f - mask_v;
                    int bgR = Color.red(bgPixel);
                    int bgG = Color.green(bgPixel);
                    int bgB = Color.blue(bgPixel);
                    int fgR = Color.red(fgPixel);
                    int fgG = Color.green(fgPixel);
                    int fgB = Color.blue(fgPixel);

                    int r = (int)(bgR * alpha + fgR * mask_v);
                    int g = (int)(bgG * alpha + fgG * mask_v);
                    int b = (int)(bgB * alpha + fgB * mask_v);
                    r = r > 255 ? 255 : r;
                    g = g > 255 ? 255 : g;
                    b = b > 255 ? 255 : b;

                    int  color = Color.argb(255, r, g, b);
                    argbPixels[idxBg] = color;
                }
            }

        }
        Bitmap bitmap = Bitmap.createBitmap(argbPixels, width, height, Bitmap.Config.ARGB_8888);

        canvas.drawBitmap(bitmap, 0, 0, mPaint);
    }
这段代码大概今天或者明天，会更新到Android demo中。

**Comment by mrbrantofgithub** [comment]
`private void blendForegroundBackground(Canvas canvas, Bitmap backImg, VNN.VNN_ImageArr foreData, VNN.VNN_ImageArr maskData) {
        if (canvas == null) {
            return;
        }
        int width = backImg.getWidth();
        int height = backImg.getHeight();
        int totalPixels = width * height;
        @ColorInt int[] argbPixels = new int[totalPixels];
        backImg.getPixels(argbPixels, 0, width, 0, 0, width, height);

        for(int i = 0; i < foreData.imgsNum; i++) {
            float cropLeftFloat = foreData.imgsArr[i].rect[0];
            float cropTopFloat = foreData.imgsArr[i].rect[1];
            float cropRightFloat = foreData.imgsArr[i].rect[2];
            float cropBottomFloat = foreData.imgsArr[i].rect[3];
            int cropLeft = (int)(cropLeftFloat * (width - 1));
            int cropTop = (int)(cropTopFloat * (height - 1));
            int cropRight = (int)(cropRightFloat * (width - 1));
            int cropBottom = (int)(cropBottomFloat * (height - 1));
            int cropWidth = cropRight - cropLeft + 1;
            int cropHeight = cropBottom - cropTop + 1;
            Bitmap maskImg = getBitmapImgFromMask(maskData.imgsArr[i].data, maskData.imgsArr[i].width, maskData.imgsArr[i].height);
            Bitmap fgImg = getBitmapImgFromRGB(foreData.imgsArr[i].data, foreData.imgsArr[i].width, foreData.imgsArr[i].height);
            Bitmap resizeMaskImg = resizeBitmap(maskImg, cropWidth, cropHeight);
            Bitmap resizefgImg = resizeBitmap(fgImg, cropWidth, cropHeight);
            int cropPixels = cropWidth * cropHeight;
            @ColorInt int[] maskPixels = new int[cropPixels];
            @ColorInt int[] fgPixels = new int[cropPixels];
            resizeMaskImg.getPixels(maskPixels, 0, cropWidth, 0, 0, cropWidth, cropHeight);
            resizefgImg.getPixels(fgPixels, 0, cropWidth, 0, 0, cropWidth, cropHeight);
            for (int h = 0; h < cropHeight; ++h) {
                int startH = cropTop + h;

                if (startH < 0) {
                    continue;
                }
                if (startH >= height) {
                    break;
                }
                for (int w = 0; w < cropWidth; ++w) {
                    int startW = cropLeft + w;
                    if (startW < 0) {
                        continue;
                    }
                    if (startW >= width) {
                        break;
                    }
                    int idxBg =startH * width + startW;

                    @ColorInt int bgPixel = argbPixels[idxBg];
                    @ColorInt int maskPixel = maskPixels[h * cropWidth + w];
                    @ColorInt int fgPixel = fgPixels[h * cropWidth + w];
                    float mask_v = Color.red(maskPixel) / 255.f;
                    float alpha = 1.0f - mask_v;
                    int bgR = Color.red(bgPixel);
                    int bgG = Color.green(bgPixel);
                    int bgB = Color.blue(bgPixel);
                    int fgR = Color.red(fgPixel);
                    int fgG = Color.green(fgPixel);
                    int fgB = Color.blue(fgPixel);

                    int r = (int)(bgR * alpha + fgR * mask_v);
                    int g = (int)(bgG * alpha + fgG * mask_v);
                    int b = (int)(bgB * alpha + fgB * mask_v);
                    r = r > 255 ? 255 : r;
                    g = g > 255 ? 255 : g;
                    b = b > 255 ? 255 : b;

                    int  color = Color.argb(255, r, g, b);
                    argbPixels[idxBg] = color;
                }
            }

        }
        Bitmap bitmap = Bitmap.createBitmap(argbPixels, width, height, Bitmap.Config.ARGB_8888);

        canvas.drawBitmap(bitmap, 0, 0, mPaint);
    }`
大概今天或者明天我会更新到Android demo中，能看到图片模式下单效果

**Comment by mrbrantofgithub** [comment]
`

private void blendForegroundBackground(Canvas canvas, Bitmap backImg, VNN.VNN_ImageArr foreData, VNN.VNN_ImageArr maskData) {
        if (canvas == null) {
            return;
        }
        int width = backImg.getWidth();
        int height = backImg.getHeight();
        int totalPixels = width * height;
        @ColorInt int[] argbPixels = new int[totalPixels];
        backImg.getPixels(argbPixels, 0, width, 0, 0, width, height);

        for(int i = 0; i < foreData.imgsNum; i++) {
            float cropLeftFloat = foreData.imgsArr[i].rect[0];
            float cropTopFloat = foreData.imgsArr[i].rect[1];
            float cropRightFloat = foreData.imgsArr[i].rect[2];
            float cropBottomFloat = foreData.imgsArr[i].rect[3];
            int cropLeft = (int)(cropLeftFloat * (width - 1));
            int cropTop = (int)(cropTopFloat * (height - 1));
            int cropRight = (int)(cropRightFloat * (width - 1));
            int cropBottom = (int)(cropBottomFloat * (height - 1));
            int cropWidth = cropRight - cropLeft + 1;
            int cropHeight = cropBottom - cropTop + 1;
            Bitmap maskImg = getBitmapImgFromMask(maskData.imgsArr[i].data, maskData.imgsArr[i].width, maskData.imgsArr[i].height);
            Bitmap fgImg = getBitmapImgFromRGB(foreData.imgsArr[i].data, foreData.imgsArr[i].width, foreData.imgsArr[i].height);
            Bitmap resizeMaskImg = resizeBitmap(maskImg, cropWidth, cropHeight);
            Bitmap resizefgImg = resizeBitmap(fgImg, cropWidth, cropHeight);
            int cropPixels = cropWidth * cropHeight;
            @ColorInt int[] maskPixels = new int[cropPixels];
            @ColorInt int[] fgPixels = new int[cropPixels];
            resizeMaskImg.getPixels(maskPixels, 0, cropWidth, 0, 0, cropWidth, cropHeight);
            resizefgImg.getPixels(fgPixels, 0, cropWidth, 0, 0, cropWidth, cropHeight);
            for (int h = 0; h < cropHeight; ++h) {
                int startH = cropTop + h;

                if (startH < 0) {
                    continue;
                }
                if (startH >= height) {
                    break;
                }
                for (int w = 0; w < cropWidth; ++w) {
                    int startW = cropLeft + w;
                    if (startW < 0) {
                        continue;
                    }
                    if (startW >= width) {
                        break;
                    }
                    int idxBg =startH * width + startW;

                    @ColorInt int bgPixel = argbPixels[idxBg];
                    @ColorInt int maskPixel = maskPixels[h * cropWidth + w];
                    @ColorInt int fgPixel = fgPixels[h * cropWidth + w];
                    float mask_v = Color.red(maskPixel) / 255.f;
                    float alpha = 1.0f - mask_v;
                    int bgR = Color.red(bgPixel);
                    int bgG = Color.green(bgPixel);
                    int bgB = Color.blue(bgPixel);
                    int fgR = Color.red(fgPixel);
                    int fgG = Color.green(fgPixel);
                    int fgB = Color.blue(fgPixel);

                    int r = (int)(bgR * alpha + fgR * mask_v);
                    int g = (int)(bgG * alpha + fgG * mask_v);
                    int b = (int)(bgB * alpha + fgB * mask_v);
                    r = r > 255 ? 255 : r;
                    g = g > 255 ? 255 : g;
                    b = b > 255 ? 255 : b;

                    int  color = Color.argb(255, r, g, b);
                    argbPixels[idxBg] = color;
                }
            }

        }
        Bitmap bitmap = Bitmap.createBitmap(argbPixels, width, height, Bitmap.Config.ARGB_8888);

        canvas.drawBitmap(bitmap, 0, 0, mPaint);
    }

`
今天或者明天我会把这段代码更新到Android Demo中，图片模式就可以看到效果

**Comment by mrbrantofgithub** [comment]
`

private void blendForegroundBackground(Canvas canvas, Bitmap backImg, VNN.VNN_ImageArr foreData, VNN.VNN_ImageArr maskData) {
        if (canvas == null) {
            return;
        }
        int width = backImg.getWidth();
        int height = backImg.getHeight();
        int totalPixels = width * height;
        @ColorInt int[] argbPixels = new int[totalPixels];
        backImg.getPixels(argbPixels, 0, width, 0, 0, width, height);
        for(int i = 0; i < foreData.imgsNum; i++) {
            float cropLeftFloat = foreData.imgsArr[i].rect[0];
            float cropTopFloat = foreData.imgsArr[i].rect[1];
            float cropRightFloat = foreData.imgsArr[i].rect[2];
            float cropBottomFloat = foreData.imgsArr[i].rect[3];
            int cropLeft = (int)(cropLeftFloat * (width - 1));
            int cropTop = (int)(cropTopFloat * (height - 1));
            int cropRight = (int)(cropRightFloat * (width - 1));
            int cropBottom = (int)(cropBottomFloat * (height - 1));
            int cropWidth = cropRight - cropLeft + 1;
            int cropHeight = cropBottom - cropTop + 1;
            Bitmap maskImg = getBitmapImgFromMask(maskData.imgsArr[i].data, maskData.imgsArr[i].width, maskData.imgsArr[i].height);
            Bitmap fgImg = getBitmapImgFromRGB(foreData.imgsArr[i].data, foreData.imgsArr[i].width, foreData.imgsArr[i].height);
            Bitmap resizeMaskImg = resizeBitmap(maskImg, cropWidth, cropHeight);
            Bitmap resizefgImg = resizeBitmap(fgImg, cropWidth, cropHeight);
            int cropPixels = cropWidth * cropHeight;
            @ColorInt int[] maskPixels = new int[cropPixels];
            @ColorInt int[] fgPixels = new int[cropPixels];
            resizeMaskImg.getPixels(maskPixels, 0, cropWidth, 0, 0, cropWidth, cropHeight);
            resizefgImg.getPixels(fgPixels, 0, cropWidth, 0, 0, cropWidth, cropHeight);
            for (int h = 0; h < cropHeight; ++h) {
                int startH = cropTop + h;

                if (startH < 0) {
                    continue;
                }
                if (startH >= height) {
                    break;
                }
                for (int w = 0; w < cropWidth; ++w) {
                    int startW = cropLeft + w;
                    if (startW < 0) {
                        continue;
                    }
                    if (startW >= width) {
                        break;
                    }
                    int idxBg =startH * width + startW;

                    @ColorInt int bgPixel = argbPixels[idxBg];
                    @ColorInt int maskPixel = maskPixels[h * cropWidth + w];
                    @ColorInt int fgPixel = fgPixels[h * cropWidth + w];
                    float mask_v = Color.red(maskPixel) / 255.f;
                    float alpha = 1.0f - mask_v;
                    int bgR = Color.red(bgPixel);
                    int bgG = Color.green(bgPixel);
                    int bgB = Color.blue(bgPixel);
                    int fgR = Color.red(fgPixel);
                    int fgG = Color.green(fgPixel);
                    int fgB = Color.blue(fgPixel);

                    int r = (int)(bgR * alpha + fgR * mask_v);
                    int g = (int)(bgG * alpha + fgG * mask_v);
                    int b = (int)(bgB * alpha + fgB * mask_v);
                    r = r > 255 ? 255 : r;
                    g = g > 255 ? 255 : g;
                    b = b > 255 ? 255 : b;

                    int  color = Color.argb(255, r, g, b);
                    argbPixels[idxBg] = color;
                }
            }

        }
        Bitmap bitmap = Bitmap.createBitmap(argbPixels, width, height, Bitmap.Config.ARGB_8888);

        canvas.drawBitmap(bitmap, 0, 0, mPaint);
    }

`
今天或者明天我会更新到Android demo中

**Comment by mrbrantofgithub** [comment]
@zhongbaitu 我更新了Android的demo，可以看图片模式下disney face和3d game face的效果，在vnnhelper.java文件中blendForegroundBackground函数实现了你的需求

**Comment by zhongbaitu** [comment]
@mrbrantofgithub  十分感谢，有点出乎意料的响应速度 ！ 大赞！
